version: '3.1'
services:
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: on-failure:8
    ports:
      - 3306:3306
    volumes:
      - oxente:/etc
    environment:
      MYSQL_ROOT_PASSWORD: pass
volumes:
  oxente:
